### ISSUE TITLE
store Color Code in URL

### ISSUE THREAD

**Issue by poyribn** [holbrookdev/ok-color-picker#1]
one thing i do often is keep multiple tabs of OK Color Picker open to create a palette.

since the color code isn't stored in the URL, i lose my picked color when reloading the page.
this isn't only a problem when i accidentally reload the page, but especially when my browser automatically puts the tab in sleep mode:

after opening the tab in sleep mode, the page has to reload, so because the color code isn't stored in the URL i have to restart with the default color.

---

YouTube player stores the video ID in the URL so that reloading the page keeps the video you meant to watch instead of returning to the start page, and it makes it possible to share videos. the format is broken down like this:
1. static part: ``https://www.youtube.com/watch?v=``
2. video ID, e.g. ``dQw4w9WgXcQ``

together they make the complete video link:
[``https://www.youtube.com/watch?v=dQw4w9WgXcQ``](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

BeepBox uses a similar format to store song data:
1. static part: ``https://www.beepbox.co/#``
2. song data, e.g. ``9n10sbk0l00e03t2Qa7g03j03r1i0o4T0v1u10f0qg01d04w2h0E0basp1RFE-430R9HYkzE8X3nViOOHb8W2ehdvBbbaIIzI8WOfcP9vgCR-X3n``

together they make the complete song link:
[``https://www.beepbox.co/#9n10sbk0l00e03t2Qa7g03j03r1i0o4T0v1u10f0qg01d04w2h0E0basp1RFE-430R9HYkzE8X3nViOOHb8W2ehdvBbbaIIzI8WOfcP9vgCR-X3n``](https://www.beepbox.co/#9n10sbk0l00e03t2Qa7g03j03r1i0o4T0v1u10f0qg01d04w2h0E0basp1RFE-430R9HYkzE8X3nViOOHb8W2ehdvBbbaIIzI8WOfcP9vgCR-X3n)

OK color picker would benefit from a similar format:
1. static part: ``https://ok-color-picker.netlify.app/#color=``
4. color code, e.g. ``aa9eef``

together these parts would make the complete color link:
``https://ok-color-picker.netlify.app/#color=aa9eef``

**Comment by holbrookdev** [comment]
Hey @Sosasees, thank you for the suggestion and for listing out the details.

Storing the color code in the URL is a great idea. I like the format where the color is stored in the hash:

`https://ok-color-picker.netlify.app/#aa9eef`

I went ahead and implemented it — about to push the update.

Cheers 🎉
